common: &default_settings
  access_key_id: AKIAJZLWPTDVMHBLG4EQ
  secret_access_key: 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

development:
  <<: *default_settings
  bucket: outcircle-development-images

test:
  <<: *default_settings
  bucket: outcircle-test-images

production:
  <<: *default_settings
  bucket: outcircle-production-images
