# -*- encoding : utf-8 -*-
class CreateLanguages < ActiveRecord::Migration
  def self.up
    create_table :languages do |t|
      t.string :name
    end

    add_index :languages, :name
["Afrikaans",
"Akan",
"Albanian",
"Amharic (Ethiopian)",
"Arabic, Egyptian",
"Arabic, Middle Eastern",
"Arabic, Moroccan",
"Arabic, other",
"Aramaic",
"Armenian",
"Assamese",
"Assyrian",
"Azerbaijani",
"Baoulé (Baule, Bawule)",
"Basque",
"Bavarian (Austro-Bavarian)",
"Belarusian",
"Bemba (Chiwemba, Wemba)",
"Bengali",
"Berber",
"Bosnian",
"Breton",
"Bulgarian",
"Burmese",
"Cambodian (Khmer)",
"Catalan",
"Cebuano (Bisaya)",
"Chichewa (Nyanja)",
"Chinese, Cantonese",
"Chinese, Mandarin",
"Chinese, other",
"Chuvash (Bulgar)",
"Creole",
"Croatian",
"Czech",
"Danish",
"Dutch",
"English",
"Esperanto",
"Estonian",
"Faroese",
"Fijian",
"Filipino (Tagalog)",
"Finnish",
"Fon (Dahomeen, Djedji, Fongbe)",
"French",
"Gaelic (Irish)",
"Gaelic (Scottish)",
"Galician",
"Georgian",
"German",
"Greek",
"Gujarati",
"Hausa",
"Hawaiian",
"Hebrew",
"Hindi",
"Hmong",
"Hungarian",
"Icelandic",
"Ido",
"Igbo (Ibo)",
"Indonesian (Bahasa)",
"Interlingua",
"Italian",
"Japanese",
"Kannada",
"Kazakh",
"Kituba (Kikoongo, Munukutuba)",
"Konkani",
"Konkani (Kunabi, Cugani, Bankoti)",
"Korean",
"Kurdish",
"Kyrgyz (Kara-Kirgiz, Kirghiz, Kirgiz)",
"Ladino",
"Lao",
"Latin",
"Latvian",
"Ligurian",
"Lingala (Ngala)",
"Lithuanian",
"Lombard",
"Luxembourgeois (Luxemburgian)",
"Macedonian",
"Malagasy",
"Malay (Bahasa Malaysia)",
"Malayalam",
"Maldivian (Dhivehi)",
"Maltese",
"Maori (New Zealand Maori)",
"Marathi",
"Mongolian",
"Montenegrin",
"Native American (Ojibway, Cree...)",
"Nepali",
"Newari",
"Norwegian",
"Nyanja (Chewa, Chinyanja)",
"Occitan (Occitani)",
"Oriya",
"Oromo (Oromoo , Oromiffa)",
"Paraguayan Guarani",
"Persian (Farsi, Dari)",
"Polish",
"Portuguese",
"Pulaar",
"Punjabi",
"Pushto (Pashto)",
"Quechua",
"Romanian",
"Romansch",
"Romany (Gypsy, Danubian)",
"Rundi (Kirundi, Urundi)",
"Russian",
"Rwanda (Kinyarwanda)",
"Saami (sami)",
"Samoan",
"Sanskrit",
"Serbian (Serbo-Croatian)",
"Shona",
"Sicilian",
"Sign Language",
"Sindhi",
"Sinhalese",
"Slovak",
"Slovenian",
"Somali",
"Spanish",
"Swahili",
"Swedish",
"Tajiki (Tajiki, Tadzhik)",
"Tamil",
"Tatar (Tartar)",
"Telugu",
"Tetum",
"Thai",
"Tibetan",
"Tigrigna (Tigray, Tigrinya)",
"Tongan",
"Tswana",
"Tumbukae",
"Turkish",
"Ukrainian",
"Urdu",
"Uyghur (Wighor)",
"Uzbek",
"Venetian",
"Vennamese",
"Welsh",
"Wolof",
"Xhosa",
"Yiddish",
"Yoruba",
"Zulu"].each do |lang|
  Language.create(:name => lang)
end
  end

  def self.down
    drop_table :languages
  end
end
