--- 
- !ruby/object:Rubber::Configuration::InstanceItem 
  domain: outcircle.com
  external_host: ec2-50-18-121-170.us-west-1.compute.amazonaws.com
  external_ip: 50.18.121.170
  instance_id: i-740e2130
  internal_host: ip-10-170-18-135.us-west-1.compute.internal
  internal_ip: 10.170.18.135
  name: web01
  platform: linux
  roles: 
  - !ruby/object:Rubber::Configuration::RoleItem 
    name: web
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: haproxy
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: app
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: passenger
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: apache
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: db
    options: 
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem 
    name: mysql_master
    options: {}

  root_device_type: ebs
  security_groups: 
  - outcircle_production_default
  - outcircle_production_web
  - outcircle_production_web01
  - outcircle_production_haproxy
  - outcircle_production_app
  - outcircle_production_passenger
  - outcircle_production_apache
  - outcircle_production_db
  - outcircle_production_mysql_master
  static_ip: 50.18.121.170
  zone: us-west-1c
- volumes: {}

  static_ips: 
    web01: 50.18.121.170
