--- 
- !ruby/object:Rubber::Configuration::InstanceItem 
  domain: iwakela.com
  external_host: ec2-50-18-120-189.us-west-1.compute.amazonaws.com
  external_ip: 50.18.120.189
  instance_id: i-58fad61c
  internal_host: ip-10-161-91-102.us-west-1.compute.internal
  internal_ip: 10.161.91.102
  name: production
  platform: linux
  roles: 
  - !ruby/object:Rubber::Configuration::RoleItem 
    name: web
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: haproxy
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: app
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: passenger
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: apache
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: db
    options: 
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem 
    name: mysql_master
    options: {}

  root_device_type: ebs
  security_groups: 
  - exview_production_default
  - exview_production_web
  - exview_production_production
  - exview_production_haproxy
  - exview_production_app
  - exview_production_passenger
  - exview_production_apache
  - exview_production_db
  - exview_production_mysql_master
  static_ip: 50.18.120.189
  zone: us-west-1a
- volumes: {}

  static_ips: 
    production: 50.18.120.189
